jubilats = input("Ets jubilat?:")
no_jubilats = int(input("Ets jubilat?:")
dones_roses = input("Ets dona i tens el cabell ros?:")
dones_restants = int( input("Ets dona i no tens el cabell ros?:")
homes_i_dones = int(input("Ets home o dona?:"))
if (edad="jubilats")
  print("no paga")
if (edad="no jubilats")
  print("1")
if (dona="cabell_ros")
  print("no paga")
if (dona="restant")
  print("0'50")
if ((edad <5> or (edad<=69)):
  print("no paga")
home_i_dona int(input("indique la edad para saber si pagan:")
if ((edad <=5) or (edad >=65)):
  print("no paga")
